language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

os:
  - linux
  - osx

before_script:
  - if [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - mkdir tests/PHPUnit/WURFL/Configuration/cache/
  - chmod -R 777 tests/PHPUnit/WURFL/Configuration/cache/

script:
  - phpunit --no-configuration --coverage-text --coverage-clover=coverage.clover --colors --verbose --bootstrap tests/PHPUnit/bootstrap.php tests/PHPUnit/WURFLTestsSuite.php

after_script:
  - rm -R -f tests/PHPUnit/WURFL/Configuration/cache/
  - rmdir tests/PHPUnit/WURFL/Configuration/cache/
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover